// Datos de las imÃ¡genes con tÃ­tulos, descripciones y caracterÃ­sticas
const images = [
	new Fotos("./img/despegando (2).png", "Despegando de Barcelona", "Inicio del viaje hacia Londres", ["Primer dÃ­a", "Barcelona-Londres", "DuraciÃ³n del vuelo: 2h 30m", "Londres: Capital de Reino Unido"]),
	new Fotos("./img/londres (2).png", "Vista de Londres desde una mochila", "Una perspectiva Ãºnica de la ciudad", ["Minomi aventurero", "Viajero", "Curioso", "Explorador urbano"]),
	new Fotos("./img/catedral.png", "Catedral de Westminster", "Uno de los monumentos mÃ¡s icÃ³nicos de Londres", ["Construida entre 1895 y 1903", "Sede principal de la Iglesia catÃ³lica en Inglaterra", "Arquitectura neobizantina", "Importante lugar religioso y turÃ­stico de Londres"]),
	new Fotos("./img/bigben.png", "El Big Ben de Londres", "La famosa torre del reloj", ["Inaugurado en 1859", "Torre mÃ¡s famosa de Londres", "SÃ­mbolo histÃ³rico del Reino Unido", "Ubicado junto al Parlamento britÃ¡nico"]),
	new Fotos("./img/phone.png", "Cabina de telÃ©fono londinense", "Las tradicionales cabinas rojas de Londres", ["Minomi en Londres", "Cabina roja icÃ³nica", "Turismo britÃ¡nico", "Foto tÃ­pica londinense"]),
	new Fotos("./img/halminton.png", "Musical Hamilton - Acto I", "Experiencia teatral en el West End", ["Minomi y Yolanda en el West End", "Musical Hamilton", "Noche de teatro en Londres", "Experiencia inolvidable"]),
	new Fotos("./img/hamilton2.png", "Musical Hamilton - Acto II", "Una noche de teatro memorable", ["Victoria Palace Theatre", "Creado por Lin-Manuel Miranda", "Estrenado en Londres en 2017", "Musical sobre la vida de Alexander Hamilton", "Ã‰xito mundial ganador de premios Tony y Olivier"]),
	new Fotos("./img/witches.png", "Musical Wicked", "La historia de las brujas del Mago de Oz", ["Apollo Victoria Theatre", "Musical creado por Stephen Schwartz", "Estrenado en Londres en 2006", "Historia no contada de las brujas de Oz", "Uno de los musicales mÃ¡s exitosos del mundo"]),
	new Fotos("./img/nottinghillb.png", "LibrerÃ­a Notting Hill", "La famosa librerÃ­a de la pelÃ­cula Notting Hill", ["The Notting Hill Bookshop", "InspirÃ³ la pelÃ­cula Notting Hill", "Barrio londinense de Notting Hill", "Lugar turÃ­stico muy visitado", "Escenario icÃ³nico del cine romÃ¡ntico"]),
	new Fotos("./img/nottinghllinside.png", "Interior de Notting Hill", "Dentro de la icÃ³nica librerÃ­a", ["Interior acogedor y cinematogrÃ¡fico", "LibrerÃ­a especializada en viajes", "Ambiente clÃ¡sico londinense", "Zona famosa por la pelÃ­cula Notting Hill", "Experiencia cultural en Londres"]),
	new Fotos("./img/nottinghillhouse.png", "Casa de la pelÃ­cula Notting Hill", "UbicaciÃ³n de rodaje principal", ["Casa azul de la pelÃ­cula Notting Hill", "Rodaje protagonizado por Julia Roberts", "PelÃ­cula estrenada en 1999", "Uno de los lugares mÃ¡s fotografiados", "SÃ­mbolo del cine romÃ¡ntico britÃ¡nico"]),
	new Fotos("./img/portobello.png", "Paseando por Portobello", "Famoso mercado de antigÃ¼edades", ["Portobello Road Market", "Mercado histÃ³rico de Londres", "Famoso por antigÃ¼edades y arte", "Ubicado en el barrio de Notting Hill", "Uno de los mercados mÃ¡s populares de Europa"]),
	new Fotos("./img/relax.png", "Tomando tÃ© en el bar de Teatro Soho", "Un momento de relajaciÃ³n", ["Barrio Soho de Londres", "TradiciÃ³n britÃ¡nica del tÃ©", "Zona famosa por teatros y musicales", "Ambiente relajado y cultural", "Descanso despuÃ©s del recorrido turÃ­stico"]),
	new Fotos("./img/puentelondres.png", "Mirando al puente de Londres", "Vistas del icÃ³nico Puente de la Torre", ["Tower Bridge de Londres", "Inaugurado en 1894", "Uno de los puentes mÃ¡s famosos del mundo", "SÃ­mbolo arquitectÃ³nico britÃ¡nico", "Vistas panorÃ¡micas del rÃ­o TÃ¡mesis"]),
	new Fotos("./img/visita.png", "Visita especial", "Un momento especial durante el viaje", ["Encuentro inesperado", "Recuerdo inolvidable", "Nueva amistad", "Foto espontÃ¡nea"]),
	new Fotos("./img/adios.png", "Despedida de Londres", "Ãšltima foto antes de regresar", ["Vista nocturna desde el aviÃ³n", "Luces de Londres al anochecer", "Regreso despuÃ©s del viaje", "Ãšltimos recuerdos de la ciudad", "Final de la aventura londinense"])
];
